# * Backend Priority Order: Core, Aqua, Github, Package Manager (cargo, npm, pipx)

[env]
HK_PKL_BACKEND = "pkl" # TODO remove once upgraded to hk v2

[tools]
"core:java" = "25.0.2"                     # Used for pkl vscode extension
"aqua:astral-sh/uv" = "0.12.16"            # Used for python (pipx) linting tools
"aqua:apple/pkl" = "0.32.1"                # Used for linting & LSP of .pkl config files
"aqua:mikefarah/yq" = "4.53.6"             # Used for validating & formatting JSON & toml parsing
"aqua:tombi-toml/tombi" = "1.5.5"          # Used for validating & formatting TOML
"aqua:EmbarkStudios/cargo-deny" = "0.20.2" # Used for auditing dependencies (hk cargo deny step)
"aqua:jdx/hk" = "2.0.1"                   # Used for linting, formatting & git hooks
"aqua:rvben/rumdl" = "0.2.73"              # Used for linting & formatting markdown
"aqua:loeffel-io/ls-lint" = "2.3.1"        # Used for enforcing folder & file naming conventions
"aqua:lycheeverse/lychee" = "0.24.2"       # Used for checking for dead links
"aqua:google/yamlfmt" = "0.21.0"           # Used for formatting YAML
"github:zizmorcore/zizmor" = "v1.30.1"     # Used for statically analyzing github actions
"github:mongodb/kingfisher" = "v2.4.0"     # Used for checking for leaked credentials & secrets
"github:kucherenko/jscpd" = "v5.2.1"       # Used for detecting code duplication
"cargo:templatry" = "0.1.0"                # Used for generating config files
"pipx:yamllint" = "1.38.0"                 # Used for linting YAML

[tools."http:dart"]
version = "3.13.4"
checksum_url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-{{ os() }}-{{ arch() }}-release.zip.sha256sum"
url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-{{ os() }}-{{ arch() }}-release.zip"
version_expr = 'fromJSON(body).prefixes | filter({ # matches "^channels/stable/release/(\\d+\\.\\d+\\.\\d+)/$" }) | map({split(#, "/")[3]}) | sortVersions()'
version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/"

[settings]
lockfile = true
